# Generated by Django 6.0.3 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_service_description_alter_booking_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
