# Generated by Django 6.0.3 on 2026-05-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mov_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
